package uz.algoexpert.todoapp.model;

public enum ActionType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_COMPLETED,
    TASK_REOPENED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_NOT_FOUND,
    INVALID_ACTION,
    ALL_COMPLETED_TASKS_RETRIEVED,
    ALL_INCOMPLETE_TASKS_RETRIEVED,
    ALL_TASKS_DELETED,
    ALL_TASKS_RETRIEVED,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    BACKEND_SERVICE_ERROR
}
